/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cubizer;

/**
 *
 * @author rnagel
 */
public class ConstructCuboidDialog extends javax.swing.JDialog implements ShapeDialog{
    private Result result = Result.CANCEL;
    
    
    /**
     * Creates new form ConstructLineDialog
     */
    public ConstructCuboidDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlDim1 = new javax.swing.JPanel();
        lblZInc1 = new javax.swing.JLabel();
        spnZInc1 = new javax.swing.JSpinner();
        lblXInc1 = new javax.swing.JLabel();
        spnLength1 = new javax.swing.JSpinner();
        lblLength1 = new javax.swing.JLabel();
        spnYInc1 = new javax.swing.JSpinner();
        lblYInc1 = new javax.swing.JLabel();
        spnXInc1 = new javax.swing.JSpinner();
        pnlDim2 = new javax.swing.JPanel();
        lblZInc2 = new javax.swing.JLabel();
        spnZInc2 = new javax.swing.JSpinner();
        lblXInc2 = new javax.swing.JLabel();
        spnLength2 = new javax.swing.JSpinner();
        lblLength2 = new javax.swing.JLabel();
        spnYInc2 = new javax.swing.JSpinner();
        lblYInc2 = new javax.swing.JLabel();
        spnXInc2 = new javax.swing.JSpinner();
        pnlDim3 = new javax.swing.JPanel();
        lblZInc3 = new javax.swing.JLabel();
        spnZInc3 = new javax.swing.JSpinner();
        lblXInc3 = new javax.swing.JLabel();
        spnLength3 = new javax.swing.JSpinner();
        lblLength3 = new javax.swing.JLabel();
        spnYInc3 = new javax.swing.JSpinner();
        lblYInc3 = new javax.swing.JLabel();
        spnXInc3 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Construct Cuboid");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        pnlDim1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dimension 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblZInc1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZInc1.setText("Z-increment:");

        spnZInc1.setModel(new javax.swing.SpinnerNumberModel(0.0d, -100.0d, 100.0d, 0.1d));

        lblXInc1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblXInc1.setText("X-increment:");

        spnLength1.setModel(new javax.swing.SpinnerNumberModel(5, 1, 1024, 1));

        lblLength1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLength1.setText("Length:");

        spnYInc1.setModel(new javax.swing.SpinnerNumberModel(0.0d, -100.0d, 100.0d, 0.1d));

        lblYInc1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYInc1.setText("Y-increment:");

        spnXInc1.setModel(new javax.swing.SpinnerNumberModel(1.0d, -100.0d, 100.0d, 0.1d));

        javax.swing.GroupLayout pnlDim1Layout = new javax.swing.GroupLayout(pnlDim1);
        pnlDim1.setLayout(pnlDim1Layout);
        pnlDim1Layout.setHorizontalGroup(
            pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDim1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLength1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblXInc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblYInc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblZInc1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnLength1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnXInc1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnYInc1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnZInc1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDim1Layout.setVerticalGroup(
            pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDim1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLength1)
                    .addComponent(spnLength1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXInc1)
                    .addComponent(spnXInc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYInc1)
                    .addComponent(spnYInc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZInc1)
                    .addComponent(spnZInc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlDim2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dimension 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblZInc2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZInc2.setText("Z-increment:");

        spnZInc2.setModel(new javax.swing.SpinnerNumberModel(0.0d, -100.0d, 100.0d, 0.1d));

        lblXInc2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblXInc2.setText("X-increment:");

        spnLength2.setModel(new javax.swing.SpinnerNumberModel(5, 1, 1024, 1));

        lblLength2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLength2.setText("Length:");

        spnYInc2.setModel(new javax.swing.SpinnerNumberModel(1.0d, -100.0d, 100.0d, 0.1d));

        lblYInc2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYInc2.setText("Y-increment:");

        spnXInc2.setModel(new javax.swing.SpinnerNumberModel(0.0d, -100.0d, 100.0d, 0.1d));

        javax.swing.GroupLayout pnlDim2Layout = new javax.swing.GroupLayout(pnlDim2);
        pnlDim2.setLayout(pnlDim2Layout);
        pnlDim2Layout.setHorizontalGroup(
            pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDim2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLength2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblXInc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblYInc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblZInc2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnLength2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnXInc2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnYInc2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnZInc2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDim2Layout.setVerticalGroup(
            pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDim2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLength2)
                    .addComponent(spnLength2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXInc2)
                    .addComponent(spnXInc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYInc2)
                    .addComponent(spnYInc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZInc2)
                    .addComponent(spnZInc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlDim3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dimension 3", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblZInc3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZInc3.setText("Z-increment:");

        spnZInc3.setModel(new javax.swing.SpinnerNumberModel(1.0d, -100.0d, 100.0d, 0.1d));

        lblXInc3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblXInc3.setText("X-increment:");

        spnLength3.setModel(new javax.swing.SpinnerNumberModel(5, 1, 1024, 1));

        lblLength3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLength3.setText("Length:");

        spnYInc3.setModel(new javax.swing.SpinnerNumberModel(0.0d, -100.0d, 100.0d, 0.1d));

        lblYInc3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYInc3.setText("Y-increment:");

        spnXInc3.setModel(new javax.swing.SpinnerNumberModel(0.0d, -100.0d, 100.0d, 0.1d));

        javax.swing.GroupLayout pnlDim3Layout = new javax.swing.GroupLayout(pnlDim3);
        pnlDim3.setLayout(pnlDim3Layout);
        pnlDim3Layout.setHorizontalGroup(
            pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDim3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLength3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblXInc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblYInc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblZInc3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnLength3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnXInc3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnYInc3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnZInc3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDim3Layout.setVerticalGroup(
            pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDim3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLength3)
                    .addComponent(spnLength3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXInc3)
                    .addComponent(spnXInc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYInc3)
                    .addComponent(spnYInc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDim3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZInc3)
                    .addComponent(spnZInc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDim3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDim2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDim3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.result = Result.CANCEL;
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.result = Result.OK;
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblLength1;
    private javax.swing.JLabel lblLength2;
    private javax.swing.JLabel lblLength3;
    private javax.swing.JLabel lblXInc1;
    private javax.swing.JLabel lblXInc2;
    private javax.swing.JLabel lblXInc3;
    private javax.swing.JLabel lblYInc1;
    private javax.swing.JLabel lblYInc2;
    private javax.swing.JLabel lblYInc3;
    private javax.swing.JLabel lblZInc1;
    private javax.swing.JLabel lblZInc2;
    private javax.swing.JLabel lblZInc3;
    private javax.swing.JPanel pnlDim1;
    private javax.swing.JPanel pnlDim2;
    private javax.swing.JPanel pnlDim3;
    private javax.swing.JSpinner spnLength1;
    private javax.swing.JSpinner spnLength2;
    private javax.swing.JSpinner spnLength3;
    private javax.swing.JSpinner spnXInc1;
    private javax.swing.JSpinner spnXInc2;
    private javax.swing.JSpinner spnXInc3;
    private javax.swing.JSpinner spnYInc1;
    private javax.swing.JSpinner spnYInc2;
    private javax.swing.JSpinner spnYInc3;
    private javax.swing.JSpinner spnZInc1;
    private javax.swing.JSpinner spnZInc2;
    private javax.swing.JSpinner spnZInc3;
    // End of variables declaration//GEN-END:variables

    @Override
    public Result getDialogResult() {
        return this.result;
    }

    public Point3d getIncrement1() {
        return new Point3d((Double)spnXInc1.getValue(), (Double)spnYInc1.getValue(), (Double)spnZInc1.getValue());
    }
    
    public Point3d getIncrement2() {
        return new Point3d((Double)spnXInc2.getValue(), (Double)spnYInc2.getValue(), (Double)spnZInc2.getValue());
    }
    
    public Point3d getIncrement3() {
        return new Point3d((Double)spnXInc3.getValue(), (Double)spnYInc3.getValue(), (Double)spnZInc3.getValue());
    }
    
    public int getLength1()
    {
        return (Integer)spnLength1.getValue();
    }
    
    public int getLength2()
    {
        return (Integer)spnLength2.getValue();
    }
    
    public int getLength3()
    {
        return (Integer)spnLength3.getValue();
    }
}
