/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cubizer;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Raymond
 */
public class ModelAliasChooser extends javax.swing.JPanel {

    /**
     * Creates new form ModelAliasChooser
     */
    
    
    public ModelAliasChooser() {
    }

    public ModelAliasChooser(String label) {
        initComponents();
        lblModelLabel.setText(label);
        DefaultComboBoxModel<Model3d> cModel = new DefaultComboBoxModel<>();
        for (int m = 0; m < Global.AllModels.size(); m++)
        {
            cModel.addElement(Global.AllModels.get(m));
        }
        cboModelChoice.setModel(cModel);
        guessAlias();
    }

    private void guessAlias()
    {
        DefaultComboBoxModel cModel = (DefaultComboBoxModel)cboModelChoice.getModel();
        for (int m = 0; m < cModel.getSize(); m++)
        {
            Model3d model = (Model3d)cModel.getElementAt(m);
            if (model.getName().toUpperCase().endsWith("_" + lblModelLabel.getText().toUpperCase()))
            {
                cboModelChoice.setSelectedIndex(m);
                return;
            }
        }
    }
    
    public String getLabel()
    {
        return lblModelLabel.getText();
    }
    
    public Model3d getModelChoice()
    {
        return (Model3d)cboModelChoice.getSelectedItem();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModelLabel = new javax.swing.JLabel();
        cboModelChoice = new javax.swing.JComboBox();

        lblModelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboModelChoice, 0, 296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cboModelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboModelChoice;
    private javax.swing.JLabel lblModelLabel;
    // End of variables declaration//GEN-END:variables
}
